version: '3.0'

services:
  task-manager:
    build: .
    container_name: task-manager
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/taskdb
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user #TODO: remove
      POSTGRES_PASSWORD: password #TODO: remove
      POSTGRES_DB: taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
